# Hardware-Optimized Docker Compose Configuration
# Generated: Sun May 25 00:18:30 EDT 2025
# Profile: high_performance
# Hardware: 16 cores, 30GB RAM, amd acceleration

# This file extends the base docker-compose.yml with hardware-specific optimizations
# Usage: docker-compose -f docker-compose.yml -f docker-compose.optimized.yml up -d

services:
  # High-resource services with dynamic limits
  tdarr:
    deploy:
      resources:
        limits:
          cpus: '9.6'
          memory: 18G
        reservations:
          cpus: '1.0'
          memory: 1G
    devices:
      - /dev/dri:/dev/dri
    environment:
      - VAAPI_DEVICE=/dev/dri/renderD128
      - AMD_HW_DECODE=1

  jellyfin:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

  sabnzbd:
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1G

  # Core services with minimal but sufficient resources
  sonarr:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  radarr:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  prowlarr:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
