[env.production]
name = "beppesarrstack-net"
compatibility_date = "2024-05-01"

# Cloudflare Pages configuration
pages_build_output_dir = "docs/.vitepress/dist"

# Environment variables (these will be set in Cloudflare dashboard)
[env.production.vars]
NODE_ENV = "production"
SITE_URL = "https://beppesarrstack.net"

# Custom domain configuration
[[env.production.route]]
pattern = "beppesarrstack.net/*"
zone_name = "beppesarrstack.net"

# Development environment
[env.development]
name = "beppesarrstack-net-dev"
compatibility_date = "2024-05-01"

[env.development.vars]
NODE_ENV = "development"
SITE_URL = "https://dev.beppesarrstack.net"