name = "beppesarrstack-net"
compatibility_date = "2024-05-01"

# Cloudflare Pages configuration
pages_build_output_dir = "docs/.vitepress/dist"

[env.production]

# Environment variables (these will be set in Cloudflare dashboard)
[env.production.vars]
NODE_ENV = "production"
SITE_URL = "https://beppesarrstack.net"

# Custom domain configuration
[[env.production.route]]
pattern = "beppesarrstack.net/*"
zone_name = "beppesarrstack.net"

# Preview environment (supported by Pages)
[env.preview]
name = "beppesarrstack-net-preview"
compatibility_date = "2024-05-01"

[env.preview.vars]
NODE_ENV = "preview"
SITE_URL = "https://preview.beppesarrstack.net"