#!/bin/bash
###############################################################################
#  update-drive-mounts.sh - Dynamically update drive mounts for JBOD setup
#  This script scans for available drives and updates docker-compose volumes
###############################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/../docker-compose.yml"
MEDIA_BASE="/media/joe"

echo "=== Scanning for available drives ==="

# Find all mounted drives under /media/joe
DRIVES=($(find "$MEDIA_BASE" -maxdepth 1 -type d -name "*TB*" 2>/dev/null | sort))

if [[ ${#DRIVES[@]} -eq 0 ]]; then
    echo "No drives found under $MEDIA_BASE"
    exit 1
fi

echo "Found ${#DRIVES[@]} drives:"
for drive in "${DRIVES[@]}"; do
    echo "  - $drive"
done

# Categorize drives by speed (based on naming convention)
FAST_DRIVES=()
SLOW_DRIVES=()

for drive in "${DRIVES[@]}"; do
    if [[ "$drive" =~ Fast ]]; then
        FAST_DRIVES+=("$drive")
    elif [[ "$drive" =~ Slow ]]; then
        SLOW_DRIVES+=("$drive")
    fi
done

echo
echo "Drive categories:"
echo "  Fast drives: ${#FAST_DRIVES[@]}"
echo "  Slow drives: ${#SLOW_DRIVES[@]}"

# Generate volume mount configuration
generate_volume_mounts() {
    local service="$1"
    local media_type="$2"
    
    echo "    volumes:"
    echo "      - ${service}_config:/config"
    
    # Mount fast drives first with priority
    local counter=1
    for drive in "${FAST_DRIVES[@]}"; do
        echo "      - $drive:/${media_type}/fast${counter}:rw"
        ((counter++))
    done
    
    # Mount slow drives for archive
    counter=1
    for drive in "${SLOW_DRIVES[@]}"; do
        echo "      - $drive:/${media_type}/archive${counter}:rw"
        ((counter++))
    done
    
    # Always mount the base media directory
    echo "      - $MEDIA_BASE:/media:rw"
    
    # Mount downloads
    echo "      - downloads_volume:/downloads"
}

# Create a docker-compose override file
cat > "$SCRIPT_DIR/../docker-compose.override.yml" << EOF
# Auto-generated by update-drive-mounts.sh
# This file provides dynamic drive mounts for JBOD configuration

services:
  sonarr:
$(generate_volume_mounts "sonarr" "tv")

  radarr:
$(generate_volume_mounts "radarr" "movies")

  readarr:
$(generate_volume_mounts "readarr" "books")

  mylar:
$(generate_volume_mounts "mylar" "comics")

  lidarr:
$(generate_volume_mounts "lidarr" "music")

  # Shared access for all media
  sabnzbd:
    volumes:
      - sabnzbd_config:/config
      - downloads_volume:/downloads
      - $MEDIA_BASE:/media:rw

  bazarr:
    volumes:
      - bazarr_config:/config
      - $MEDIA_BASE:/media:rw

  # File sharing services need full access
  samba:
    volumes:
      - $MEDIA_BASE:/media/joe:rw
      - /home/joe/usenet/downloads:/downloads:rw
      - /home/joe/usenet/config:/config:rw

  nfs-server:
    volumes:
      - $MEDIA_BASE:/media/joe:rw
      - /home/joe/usenet/downloads:/downloads:rw
      - /home/joe/usenet/config:/config:rw
EOF

echo
echo "=== Generated docker-compose.override.yml ==="
echo "This file will automatically mount all available drives"
echo
echo "To apply changes:"
echo "  cd /home/joe/usenet"
echo "  docker compose down"
echo "  docker compose up -d"
echo
echo "Drive mount structure:"
echo "  - Fast drives mounted as: /tv/fast1, /tv/fast2, etc."
echo "  - Slow drives mounted as: /tv/archive1, /tv/archive2, etc."
echo "  - All drives accessible via: /media/*"